### PR TITLE
Compute bin centers as medians of the data points

### PR DESCRIPTION
**Pull request by EvgeniiChaikin**
We have decided to make bin centers be computed as the medians of the data points inside the bins 

**Result:** [LINK](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/DEC2020/L006N188/NO_EOS/z0.0_2E51_FKIN03_VKICK050_BOOST01/)

### CODE REVIEW

**Comment by EvgeniiChaikin** [comment]
Not sure we should also make this change for the mean line. For now, I left it as is

**Comment by EvgeniiChaikin** [comment]
@JBorrow I was getting the **inconsistent-units error** when I tried to use `ax.scatter(additional_points_x,additional_points_y)` in place of `ax.scatter(additional_points_x.value, additional_points_y.value)`, in the last line of the code I added to `lines.py`. However, when I looked at the units of `additional_points_x` and `additional_points_y` and compared them to the other dimensional arrays attached to the ax (`centers` & `heights`), the units seemed consistent to me. Do you know why matplotlib thinks the units are inconsistent in the former case?

**Comment by JBorrow** [comment]
Looks good, but maybe we should make the same change for the mean lines too to keep things consistent.

**Comment by JBorrow** [comment]
If you can show the full error maybe we can figure out what's going wrong there. I guess it might be mad when your additional points have a length of zero?

**Comment by EvgeniiChaikin** [comment]
> If you can show the full error maybe we can figure out what's going wrong there. I guess it might be mad when your additional points have a length of zero?

If I add a simple print statement to see the units and strip `.value` off the` additional_x,y `arrays (see the code below)

```
        for u in [centers.units, heights.units, additional_x.units, additional_y.units]:
            print("UNITS:", u)

        ax.scatter(additional_x, additional_y, color=line.get_color())
```

then I get the following output, error, and backtrace

```
Creating figures:   2%|██▊                                                                                                                                                                        | 2/122 [00:01<01:56,  1.03it/s]Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
UNITS: Msun
UNITS: mh/cm**3
UNITS: Msun
UNITS: mh/cm**3
Unable to create plot stellar_birth_density_stellar_mass_average_of_log_all_100 due to an error when trying to convert units. This likely means that you are trying to set the output units for your plot to something not dimensionally consistent with your catalogue. The error may also be in your registration file, if you are using one and this failure was on a figure using registered quantities.
Traceback:
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 1025, in create_plots
    file_extension=file_extension,
  File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 906, in make_plot
    fig.savefig(f"{directory}/{self.filename}.{file_extension}")
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/evgenii/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

```

**Comment by EvgeniiChaikin** [comment]
> Looks good, but maybe we should make the same change for the mean lines too to keep things consistent.

Done

**Comment by JBorrow** [comment]
Let's figure out the crashing bug above before merging.

**Pull request merged**
