### PR TITLE
Add registration function for HI and H_2 masses in apertures.

### PR DESCRIPTION
**Pull request by MatthieuSchaller**
To test things: `/cosma7/data/dp004/jlvc76/COLIBRE/cold_gas/haloes.properties.0`

### CODE REVIEW

**Comment by MatthieuSchaller** [comment]
FYI: The changes have been merged into VR itself and the SWIFT default VR config files have been changed.

**Comment by JBorrow** [comment]
Is there a specific reason why these are two separate functions, rather than being combined into one?

**Comment by JBorrow** [comment]
Your species masses are available under `gas_species_masses.{HI,H2}_mass_{...}_kpc`

**Comment by MatthieuSchaller** [comment]
Thanks that's indeed a much cleaner version.

**Pull request merged**
